Vagrant.configure("2") do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--cpus", "2"]
  end

  config.vm.define :dhc1 do |dhc1|
    dhc1.vm.hostname = "dhc1"
    dhc1.vm.network :private_network, ip: "192.168.42.100"
    dhc1.vm.provision "shell", :path => "dhc1.sh"

    dhc1.vm.provider :virtualbox do |vb1|
       vb1.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
       vb1.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  config.vm.define :dhc2 do |dhc2|
    dhc2.vm.hostname = "dhc2"
    dhc2.vm.network :private_network, ip: "192.168.42.110"
    dhc2.vm.provision "shell", :path => "dhc2.sh"

    dhc2.vm.provider :virtualbox do |vb2|
       vb2.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
       vb2.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  config.vm.define :dhc3 do |dhc3|
    dhc3.vm.hostname = "dhc3"
    dhc3.vm.network :private_network, ip: "192.168.42.120"
    dhc3.vm.provision "shell", :path => "dhc3.sh"

    dhc3.vm.provider :virtualbox do |vb3|
       vb3.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
       vb3.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
end
