Vagrant.configure("2") do |config|

  config.vm.box = "precise64node"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--cpus", "2"]
  end

  config.vm.define :node1 do |node1|
    node1.vm.hostname = "node1"
    node1.vm.network :private_network, ip: "192.168.42.100"
    node1.vm.provision "shell", :path => "node1.sh"

    node1.vm.provider :virtualbox do |vb1|
       vb1.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
       vb1.customize ["modifyvm", :id, "--memory", "2048"]
    end
  end

  config.vm.define :node2 do |node2|
    node2.vm.hostname = "node2"
    node2.vm.network :private_network, ip: "192.168.42.110"
    node2.vm.provision "shell", :path => "node2.sh"

    node2.vm.provider :virtualbox do |vb2|
       vb2.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
       vb2.customize ["modifyvm", :id, "--memory", "2048"]
    end
  end

  config.vm.define :node3 do |node3|
    node3.vm.hostname = "node3"
    node3.vm.network :private_network, ip: "192.168.42.120"
    node3.vm.provision "shell", :path => "node3.sh"

    node3.vm.provider :virtualbox do |vb3|
       vb3.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
       vb3.customize ["modifyvm", :id, "--memory", "2048"]
    end
  end

config.vm.box = "precise64node"
config.vm.box = "precise64node.box"

config.vm.define :home1 do |home1|
    home1.vm.hostname = "home1"
    home1.vm.network :private_network, ip: "192.168.82.100"
    home1.vm.provision "shell", :path => "home1.sh"

    home1.vm.provider :virtualbox do |vb|
       vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
       vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

   config.vm.define :home2 do |home2|
    home2.vm.hostname = "home2"
    home2.vm.network :private_network, ip: "192.168.82.110"
    home2.vm.provision "shell", :path => "home2.sh"

    home2.vm.provider :virtualbox do |vb|
       vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
       vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

   config.vm.define :home3 do |home3|
    home3.vm.hostname = "home3"
    home3.vm.network :private_network, ip: "192.168.82.120"
    home3.vm.provision "shell", :path => "home3.sh"

    home3.vm.provider :virtualbox do |vb|
       vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
       vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

   config.vm.define :monitor do |monitor|
    monitor.vm.hostname = "monitor"
    monitor.vm.network :private_network, ip: "192.168.82.190"
    monitor.vm.provision "shell", :path => "monitor.sh"

    monitor.vm.provider :virtualbox do |vb|
       vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
       vb.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
end
